package org.apache.datawise.backend.ai.semantic;

import org.apache.datawise.backend.common.support.IdGenerator;
import org.apache.datawise.backend.configstore.SemanticMetricStore;
import org.apache.datawise.backend.ai.tag.AiTableTagService;
import org.apache.datawise.backend.database.table.TableDetailService;
import org.apache.datawise.backend.domain.AutoGenerateSemanticMetricsRequest;
import org.apache.datawise.backend.domain.SaveSemanticMetricRequest;
import org.apache.datawise.backend.domain.SemanticMetricDto;
import org.apache.datawise.backend.domain.TablePropertiesResult;
import org.apache.datawise.backend.model.ConnectionEntity;
import org.apache.datawise.backend.model.SemanticMetricEntry;
import org.apache.datawise.backend.service.ConnectionVisibilityService;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

@Service
public class SemanticLayerService {

    private final SemanticMetricStore metricStore;
    private final TableDetailService tableDetailService;
    private final ConnectionVisibilityService connectionVisibilityService;
    private final AiTableTagService tableTagService;

    public SemanticLayerService(
            SemanticMetricStore metricStore,
            TableDetailService tableDetailService,
            ConnectionVisibilityService connectionVisibilityService,
            AiTableTagService tableTagService
    ) {
        this.metricStore = metricStore;
        this.tableDetailService = tableDetailService;
        this.connectionVisibilityService = connectionVisibilityService;
        this.tableTagService = tableTagService;
    }

    public List<SemanticMetricDto> list(String connectionId, String database) {
        List<SemanticMetricEntry> entries = connectionId != null && !connectionId.isBlank()
                ? metricStore.listScoped(connectionId, database)
                : metricStore.listAll();
        return entries.stream()
                .sorted(Comparator.comparing(SemanticMetricEntry::getName, String.CASE_INSENSITIVE_ORDER))
                .map(SemanticMetricDto::from)
                .toList();
    }

    public SemanticMetricDto save(SaveSemanticMetricRequest request) {
        if (request.name() == null || request.name().isBlank()) {
            throw new IllegalArgumentException("name is required");
        }
        SemanticMetricEntry entry = request.id() != null && !request.id().isBlank()
                ? findExisting(request.id())
                : new SemanticMetricEntry();
        if (entry.getId() == null) {
            entry.setId(IdGenerator.shortId("metric-"));
        }
        String previousExpression = trimOrNull(entry.getExpression());
        entry.setConnectionId(trimOrNull(request.connectionId()));
        entry.setDatabase(trimOrNull(request.database()));
        entry.setName(request.name().trim());
        entry.setExpression(trimOrNull(request.expression()));
        entry.setDescription(trimOrNull(request.description()));
        entry.setUnit(trimOrNull(request.unit()));
        entry.setOwner(trimOrNull(request.owner()));
        entry.setRelatedTables(request.relatedTables() != null ? request.relatedTables() : List.of());
        entry.setUpstreamMetrics(request.upstreamMetrics() != null ? request.upstreamMetrics() : List.of());
        applyDefinitionVersion(entry, previousExpression, trimOrNull(request.changeNote()));
        entry.setAutoGenerated(false);
        metricStore.upsert(entry);
        return SemanticMetricDto.from(entry);
    }

    public void delete(String id) {
        findExisting(id);
        metricStore.removeById(id);
    }

    /**
     * 从 Schema 表/列注释自动生成基础数据字典条目。
     */
    public List<SemanticMetricDto> autoGenerate(AutoGenerateSemanticMetricsRequest request) {
        if (request.connectionId() == null || request.connectionId().isBlank()) {
            throw new IllegalArgumentException("connectionId is required");
        }
        if (request.database() == null || request.database().isBlank()) {
            throw new IllegalArgumentException("database is required");
        }
        requireConnection(request.connectionId());

        List<SemanticMetricEntry> existing = metricStore.listScoped(request.connectionId(), request.database());
        Set<String> existingKeys = new LinkedHashSet<>();
        for (SemanticMetricEntry entry : existing) {
            existingKeys.add(metricKey(entry));
        }

        List<SemanticMetricEntry> generated = new ArrayList<>();
        List<String> tables = listTableNames(request.connectionId(), request.database());
        for (String table : tables) {
            TablePropertiesResult props = tryLoadProperties(table, request.connectionId(), request.database());
            if (props == null) {
                continue;
            }
            String tableComment = props.comment();
            if (tableComment != null && !tableComment.isBlank()) {
                String metricName = table + " \u8868";
                String key = metricKey(metricName);
                if (!existingKeys.contains(key)) {
                    SemanticMetricEntry entry = buildAutoEntry(
                            request.connectionId(),
                            request.database(),
                            metricName,
                            tableComment,
                            List.of(table)
                    );
                    generated.add(entry);
                    existingKeys.add(key);
                }
            }
            if (props.columns() != null) {
                props.columns().forEach(column -> {
                    String comment = column.comment();
                    if (comment == null || comment.isBlank()) {
                        return;
                    }
                    String metricName = table + "." + column.name();
                    String key = metricKey(metricName);
                    if (existingKeys.contains(key)) {
                        return;
                    }
                    generated.add(buildAutoEntry(
                            request.connectionId(),
                            request.database(),
                            metricName,
                            comment,
                            List.of(table)
                    ));
                    existingKeys.add(key);
                });
            }
        }

        List<SemanticMetricEntry> merged = new ArrayList<>(existing);
        for (SemanticMetricEntry entry : generated) {
            merged.add(metricStore.upsert(entry));
        }
        return merged.stream().map(SemanticMetricDto::from).toList();
    }

    private SemanticMetricEntry buildAutoEntry(
            String connectionId,
            String database,
            String name,
            String description,
            List<String> relatedTables
    ) {
        SemanticMetricEntry entry = new SemanticMetricEntry();
        entry.setId(IdGenerator.shortId("metric-"));
        entry.setConnectionId(connectionId);
        entry.setDatabase(database);
        entry.setName(name);
        entry.setDescription(description);
        entry.setRelatedTables(relatedTables);
        entry.setUpstreamMetrics(List.of());
        entry.setDefinitionVersion(1);
        entry.setDefinitionUpdatedAt(System.currentTimeMillis());
        entry.setLatestChangeNote("auto-generated");
        entry.setAutoGenerated(true);
        entry.setExpression(null);
        return entry;
    }

    private static void applyDefinitionVersion(SemanticMetricEntry entry, String previousExpression, String changeNote) {
        int currentVersion = entry.getDefinitionVersion() != null && entry.getDefinitionVersion() > 0
                ? entry.getDefinitionVersion()
                : 1;
        String currentExpression = trimOrNull(entry.getExpression());
        boolean changed = !equalsNullable(previousExpression, currentExpression);
        if (entry.getDefinitionVersion() == null) {
            entry.setDefinitionVersion(1);
            entry.setDefinitionUpdatedAt(System.currentTimeMillis());
            entry.setLatestChangeNote(changeNote);
            return;
        }
        if (!changed) {
            if (entry.getDefinitionUpdatedAt() == null) {
                entry.setDefinitionUpdatedAt(System.currentTimeMillis());
            }
            if (entry.getLatestChangeNote() == null || entry.getLatestChangeNote().isBlank()) {
                entry.setLatestChangeNote(changeNote);
            }
            return;
        }
        entry.setDefinitionVersion(currentVersion + 1);
        entry.setDefinitionUpdatedAt(System.currentTimeMillis());
        entry.setLatestChangeNote(changeNote);
    }

    private static boolean equalsNullable(String left, String right) {
        if (left == null) {
            return right == null;
        }
        return left.equals(right);
    }

    private static String metricKey(SemanticMetricEntry entry) {
        String nameKey = metricKey(entry.getName());
        return !nameKey.isBlank() ? nameKey : entry.getId();
    }

    private static String metricKey(String name) {
        return name != null ? name.toLowerCase(Locale.ROOT) : "";
    }

    private SemanticMetricEntry findExisting(String id) {
        return metricStore.listAll().stream()
                .filter(entry -> id.equals(entry.getId()))
                .findFirst()
                .orElseThrow(() -> new IllegalArgumentException("metric not found: " + id));
    }

    private ConnectionEntity requireConnection(String connectionId) {
        return connectionVisibilityService.resolveConnectionEntity(connectionId)
                .orElseThrow(() -> new IllegalArgumentException("connection not found: " + connectionId));
    }

    private List<String> listTableNames(String connectionId, String database) {
        return tableTagService.listTaggedTableNames(connectionId, database);
    }

    private TablePropertiesResult tryLoadProperties(String table, String connectionId, String database) {
        try {
            return tableDetailService.loadProperties(table, connectionId, database);
        } catch (Exception ex) {
            return null;
        }
    }

    private static String trimOrNull(String value) {
        if (value == null) {
            return null;
        }
        String trimmed = value.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }
}
