import type {DbType} from '@/core/types'

export const DB_TYPE_LABELS: Record<DbType, string> = {
    mysql: 'MySQL',
    oracle: 'Oracle',
    postgresql: 'PostgreSQL',
    sqlserver: 'SQL Server',
    mariadb: 'MariaDB',
    clickhouse: 'ClickHouse',
    dm: 'DM',
    oscar: 'Oscar',
    presto: 'Presto',
    trino: 'Trino',
    db2: 'DB2',
    redis: 'Redis',
    kafka: 'Kafka',
    yarn: 'YARN',
    mongodb: 'MongoDB',
    sqlite: 'SQLite',
    hive: 'Hive',
    oceanbase: 'OceanBase',
    kingbase: 'KingBase',
    greenplum: 'Greenplum',
    opengauss: 'openGauss',
    highgo: 'HighGo',
    gbase8a: 'GBase 8a',
    elasticsearch: 'Elasticsearch',
    kylin: 'Apache Kylin',
    starrocks: 'StarRocks',
    doris: 'Apache Doris',
    tidb: 'TiDB',
    tdengine: 'TDengine',
    sybase: 'Sybase',
    phoenix: 'Phoenix',
    cachedb: 'Caché',
    h2: 'H2',
    hsql: 'HSQLDB',
    generic: 'Generic JDBC',
    other: 'Other JDBC',
    dameng: 'Dameng',
    gaussdb: 'GaussDB',
    flink: 'Flink',
    ssh: 'SSH',
}

/** 常用数据库类型，新建连接菜单优先展示 */
export const PRIMARY_DB_TYPES: DbType[] = [
    'mysql',
    'postgresql',
    'oracle',
    'sqlserver',
    'redis',
    'kafka',
    'yarn',
    'ssh',
    'mongodb',
    'clickhouse',
    'starrocks',
    'doris',
    'sqlite',
]

export const ALL_DB_TYPES: DbType[] = [
    ...PRIMARY_DB_TYPES,
    'mariadb',
    'dm',
    'oscar',
    'presto',
    'trino',
    'db2',
    'hive',
    'oceanbase',
    'kingbase',
    'greenplum',
    'opengauss',
    'highgo',
    'gbase8a',
    'elasticsearch',
    'kylin',
    'tidb',
    'tdengine',
    'sybase',
    'phoenix',
    'cachedb',
    'h2',
    'hsql',
    'gaussdb',
    'generic',
    'other',
    'flink',
    'ssh',
]

export const DEFAULT_PORTS: Partial<Record<DbType, string>> = {
    mysql: '3306',
    oracle: '1521',
    postgresql: '5432',
    sqlserver: '1433',
    mariadb: '3306',
    clickhouse: '8123',
    dm: '5236',
    oscar: '2003',
    presto: '18080',
    trino: '8080',
    db2: '50000',
    redis: '6379',
    kafka: '9092',
    yarn: '8088',
    mongodb: '27017',
    sqlite: '',
    hive: '10000',
    oceanbase: '2881',
    kingbase: '54321',
    greenplum: '5432',
    opengauss: '15432',
    highgo: '5866',
    gbase8a: '5258',
    elasticsearch: '9200',
    kylin: '7070',
    starrocks: '9030',
    doris: '9030',
    tidb: '9030',
    tdengine: '6041',
    sybase: '5000',
    phoenix: '8765',
    cachedb: '1972',
    h2: '9092',
    hsql: '9001',
    generic: '10000',
    other: '10000',
    dameng: '5236',
    gaussdb: '8000',
    flink: '8083',
    ssh: '22',
}
