# GENERIC
generic.quote=`
generic.displayName=Generic JDBC
generic.driver=
generic.port=10000
generic.sql=
generic.urlPrefix=
generic.url=jdbc:{subprotocol}://{host}[:{port}]/[{database}][\?{params}]
generic.sample=
generic.fieldIde=ORIGINAL
generic.catalog.kind=jdbcCustom
generic.catalog.primary=false
generic.catalog.jdbcDriverRequired=true
generic.catalog.driverMaven=
generic.catalog.defaultDriverClassOverride=

# MYSQL
mysql.quote=`
mysql.displayName=MySQL
mysql.driver=com.mysql.cj.jdbc.Driver
mysql.port=3306
mysql.sql=/* ping */ SELECT 1
mysql.urlPrefix=jdbc:mysql://
mysql.url=jdbc:mysql://{host}[:{port}]/[{database}][\?{params}]
mysql.sample=jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&rewriteBatchedStatements=true&useCompression=true
mysql.fieldIde=ORIGINAL
mysql.catalog.primary=true
mysql.catalog.jdbcDriverRequired=true
mysql.catalog.driverMaven=com.mysql:mysql-connector-j:8.4.0
mysql.catalog.defaultDriverClassOverride=

# MARIADB
mariadb.quote=`
mariadb.displayName=MariaDB
mariadb.driver=org.mariadb.jdbc.Driver
mariadb.port=3306
mariadb.sql=SELECT 1
mariadb.urlPrefix=jdbc:mariadb://
mariadb.url=jdbc:mariadb://{host}[:{port}]/[{database}][\?{params}]
mariadb.sample=jdbc:mariadb://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&rewriteBatchedStatements=true&useCompression=true
mariadb.fieldIde=ORIGINAL
mariadb.catalog.primary=false
mariadb.catalog.jdbcDriverRequired=true
mariadb.catalog.driverMaven=org.mariadb.jdbc:mariadb-java-client:3.4.1
mariadb.catalog.defaultDriverClassOverride=

# ORACLE
oracle.quote="
oracle.displayName=Oracle
oracle.driver=oracle.jdbc.driver.OracleDriver
oracle.port=1521
oracle.sql=SELECT 'Hello' from DUAL
oracle.urlPrefix=jdbc:oracle:thin:@
oracle.url.0=jdbc:oracle:thin:@{host}:{port}:{database}
oracle.url.1=jdbc:oracle:thin:@//{host}[:{port}]/{database}
oracle.sample=jdbc:oracle:thin:@127.0.0.1:1521:ORCL
oracle.fieldIde=ORIGINAL
oracle.catalog.primary=false
oracle.catalog.jdbcDriverRequired=true
oracle.catalog.driverMaven=com.oracle.database.jdbc:ojdbc11:23.5.0.24.07
oracle.catalog.defaultDriverClassOverride=oracle.jdbc.OracleDriver

# SQLSERVER
sqlserver.quote=[
sqlserver.displayName=SqlServer
sqlserver.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
sqlserver.port=1433
sqlserver.sql=SELECT 1+2 as a
sqlserver.urlPrefix=jdbc:sqlserver://
sqlserver.url=jdbc:sqlserver://{host}[:{port}][;DatabaseName={database}][;{params}]
sqlserver.sample=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=test
sqlserver.fieldIde=ORIGINAL
sqlserver.catalog.primary=false
sqlserver.catalog.jdbcDriverRequired=true
sqlserver.catalog.driverMaven=com.microsoft.sqlserver:mssql-jdbc:12.8.1.jre11
sqlserver.catalog.defaultDriverClassOverride=

# POSTGRESQL
postgresql.quote="
postgresql.displayName=PostgreSql
postgresql.driver=org.postgresql.Driver
postgresql.port=5432
postgresql.sql=SELECT 1
postgresql.urlPrefix=jdbc:postgresql://
postgresql.url=jdbc:postgresql://{host}[:{port}]/[{database}][\?{params}]
postgresql.sample=jdbc:postgresql://127.0.0.1:5432/test
postgresql.fieldIde=ORIGINAL
postgresql.catalog.primary=true
postgresql.catalog.jdbcDriverRequired=true
postgresql.catalog.driverMaven=org.postgresql:postgresql:42.7.4
postgresql.catalog.defaultDriverClassOverride=

# DB2
db2.quote="
db2.displayName=DB2
db2.driver=com.ibm.db2.jcc.DB2Driver
db2.port=50000
db2.sql=SELECT 1 FROM SYSIBM.SYSDUMMY1
db2.urlPrefix=jdbc:db2://
db2.url=jdbc:db2://{host}:{port}/{database}[:{params}]
db2.sample=jdbc:db2://127.0.0.1:50000/testdb:driverType=4;fullyMaterializeLobData=true;fullyMaterializeInputStreams=true;progressiveStreaming=2;progresssiveLocators=2;
db2.fieldIde=ORIGINAL
db2.catalog.primary=false
db2.catalog.jdbcDriverRequired=true
db2.catalog.driverMaven=com.ibm.db2:jcc:11.5.9.0
db2.catalog.defaultDriverClassOverride=com.ibm.db2.jcc.DB2Driver

# DM
dm.quote="
dm.displayName=DM
dm.driver=dm.jdbc.driver.DmDriver
dm.port=5236
dm.sql=SELECT 'Hello' from DUAL
dm.urlPrefix=jdbc:dm://
dm.url=jdbc:dm://{host}:{port}[/{database}][\?{params}]
dm.sample=jdbc:dm://127.0.0.1:5236
dm.fieldIde=ORIGINAL
dm.catalog.primary=false
dm.catalog.jdbcDriverRequired=true
dm.catalog.driverMaven=com.dameng:DmJdbcDriver18:8.1.3.140
dm.catalog.defaultDriverClassOverride=dm.jdbc.driver.DmDriver

# KINGBASE
kingbase.quote="
kingbase.displayName=KingBase
kingbase.driver=com.kingbase8.Driver
kingbase.port=54321
kingbase.sql=SELECT 1
kingbase.urlPrefix=jdbc:kingbase8://
kingbase.url=jdbc:kingbase8://{host}[:{port}]/[{database}][\?{params}]
kingbase.sample=jdbc:kingbase8://127.0.0.1:54321/test
kingbase.fieldIde=ORIGINAL
kingbase.catalog.primary=false
kingbase.catalog.jdbcDriverRequired=true
kingbase.catalog.driverMaven=cn.com.kingbase:kingbase8:9.0.0
kingbase.catalog.defaultDriverClassOverride=com.kingbase8.Driver

# OSCAR
oscar.quote="
oscar.displayName=Oscar
oscar.driver=com.oscar.Driver
oscar.port=2003
oscar.sql=SELECT 1
oscar.urlPrefix=jdbc:oscar://
oscar.url=jdbc:oscar://{host}[:{port}]/[{database}][\?{params}]
oscar.sample=jdbc:oscar://127.0.0.1:2003/OSCRDB
oscar.fieldIde=ORIGINAL
oscar.catalog.primary=false
oscar.catalog.jdbcDriverRequired=true
oscar.catalog.driverMaven=com.oscar:oscarJDBC:7.0.8
oscar.catalog.defaultDriverClassOverride=com.oscar.Driver

# GBASE8A
gbase8a.quote=`
gbase8a.displayName=GBase8A
gbase8a.driver=com.gbase.jdbc.Driver
gbase8a.port=5258
gbase8a.sql=/* ping */ SELECT 1
gbase8a.urlPrefix=jdbc:gbase://
gbase8a.url=jdbc:gbase://{host}[:{port}]/[{database}][\?{params}]
gbase8a.sample=jdbc:gbase://127.0.0.1:5258/test
gbase8a.fieldIde=ORIGINAL
gbase8a.catalog.primary=false
gbase8a.catalog.jdbcDriverRequired=true
gbase8a.catalog.driverMaven=com.gbase:gbase-connector-java:9.5.0.10
gbase8a.catalog.defaultDriverClassOverride=com.gbase.jdbc.Driver

# HIGHGO
highgo.quote="
highgo.displayName=HighGo
highgo.driver=com.highgo.jdbc.Driver
highgo.port=5866
highgo.sql=SELECT 1
highgo.urlPrefix=jdbc:highgo://
highgo.url=jdbc:highgo://{host}[:{port}]/[{database}][\?{params}]
highgo.sample=jdbc:highgo://127.0.0.1:5866/highgo
highgo.fieldIde=ORIGINAL
highgo.catalog.primary=false
highgo.catalog.jdbcDriverRequired=true
highgo.catalog.driverMaven=com.highgo:HgdbJdbc:6.2.4
highgo.catalog.defaultDriverClassOverride=com.highgo.jdbc.Driver

# SYBASE
sybase.quote="
sybase.displayName=Sybase
sybase.driver=com.sybase.jdbc4.jdbc.SybDriver
sybase.port=5000
sybase.sql=SELECT 1+2 as a
sybase.urlPrefix=jdbc:sybase:Tds:
sybase.url=jdbc:sybase:Tds:{host}[:{port}][/{database}][\?{params}]
sybase.sample=jdbc:sybase:Tds:127.0.0.1:5000/test?charset=cp936
sybase.fieldIde=ORIGINAL
sybase.catalog.primary=false
sybase.catalog.jdbcDriverRequired=true
sybase.catalog.driverMaven=com.sybase.jdbc4.jdbc:jconn4:16.0
sybase.catalog.defaultDriverClassOverride=com.sybase.jdbc4.jdbc.SybDriver

# HIVE
hive.quote=`
hive.displayName=Hive
hive.driver=org.apache.hive.jdbc.HiveDriver
hive.port=10000
hive.sql=SELECT 1
hive.urlPrefix=jdbc:hive2://
hive.url=jdbc:hive2://{host}[:{port}]/[{database}][\?{params}]
hive.sample=jdbc:hive2://172.17.2.12:10000/default
hive.fieldIde=ORIGINAL
hive.catalog.primary=false
hive.catalog.jdbcDriverRequired=true
hive.catalog.driverMaven=org.apache.hive:hive-jdbc:3.1.2
hive.catalog.defaultDriverClassOverride=

# SQLITE3
sqlite3.quote="
sqlite3.displayName=Sqlite3
sqlite3.driver=org.sqlite.JDBC
sqlite3.port=0
sqlite3.sql=SELECT 1
sqlite3.urlPrefix=jdbc:sqlite:
sqlite3.url.0=jdbc:sqlite:{file}
sqlite3.url.1=jdbc:sqlite::resource:{file}
sqlite3.sample=jdbc:sqlite:/tmp/test.db
sqlite3.fieldIde=ORIGINAL
sqlite3.catalog.primary=false
sqlite3.catalog.jdbcDriverRequired=true
sqlite3.catalog.driverMaven=org.xerial:sqlite-jdbc:3.46.1.3
sqlite3.catalog.defaultDriverClassOverride=org.sqlite.JDBC

# OPENGAUSS
opengauss.quote="
opengauss.displayName=OpenGauss
opengauss.driver=org.opengauss.Driver
opengauss.port=15432
opengauss.sql=SELECT 1
opengauss.urlPrefix=jdbc:opengauss://
opengauss.url=jdbc:opengauss://{host}[:{port}]/[{database}][\?{params}]
opengauss.sample=jdbc:opengauss://127.0.0.1:15432/test
opengauss.fieldIde=ORIGINAL
opengauss.catalog.primary=false
opengauss.catalog.jdbcDriverRequired=true
opengauss.catalog.driverMaven=org.opengauss:opengauss-jdbc:5.0.0
opengauss.catalog.defaultDriverClassOverride=org.opengauss.Driver

# CLICKHOUSE
clickhouse.quote=`
clickhouse.displayName=ClickHouse
clickhouse.driver=com.clickhouse.jdbc.ClickHouseDriver
clickhouse.port=8123
clickhouse.sql=SELECT 1
clickhouse.urlPrefix=jdbc:clickhouse://
clickhouse.url=jdbc:clickhouse://{host}[:{port}]/[{database}][\?{params}]
clickhouse.sample=jdbc:clickhouse://127.0.0.1:8123/default
clickhouse.fieldIde=ORIGINAL
clickhouse.catalog.primary=false
clickhouse.catalog.jdbcDriverRequired=true
clickhouse.catalog.driverMaven=com.clickhouse:clickhouse-jdbc:0.6.5
clickhouse.catalog.defaultDriverClassOverride=com.clickhouse.jdbc.ClickHouseDriver

# MONGODB
mongodb.quote="
mongodb.displayName=MongoDB
mongodb.driver=
mongodb.port=27017
mongodb.sql=
mongodb.urlPrefix=
mongodb.url=mongodb://{host}[:{port}]/[{database}][\?{params}]
mongodb.sample=mongodb://127.0.0.1:27017/admin?authSource=admin
mongodb.fieldIde=ORIGINAL
mongodb.catalog.kind=nonJdbc
mongodb.catalog.primary=true
mongodb.catalog.jdbcDriverRequired=false
mongodb.catalog.driverMaven=
mongodb.catalog.defaultDriverClassOverride=

# ELASTICSEARCH
elasticsearch.quote="
elasticsearch.displayName=ElasticSearch
elasticsearch.driver=org.elasticsearch.xpack.sql.jdbc.EsDriver
elasticsearch.port=9200
elasticsearch.sql=SELECT 1
elasticsearch.urlPrefix=jdbc:es://
elasticsearch.url=jdbc:es://{host}[:{port}][\?{params}]
elasticsearch.sample=jdbc:es://127.0.0.1:9200
elasticsearch.fieldIde=ORIGINAL
elasticsearch.catalog.primary=false
elasticsearch.catalog.jdbcDriverRequired=true
elasticsearch.catalog.driverMaven=org.elasticsearch.plugin:x-pack-sql-jdbc:8.17.5
elasticsearch.catalog.defaultDriverClassOverride=org.elasticsearch.xpack.sql.jdbc.EsDriver

# KYLIN
kylin.quote="
kylin.displayName=Kylin
kylin.driver=org.apache.kylin.jdbc.Driver
kylin.port=7070
kylin.sql=SELECT 1
kylin.urlPrefix=jdbc:kylin://
kylin.url=jdbc:kylin://{host}[:{port}]/[{database}][\?{params}]
kylin.sample=jdbc:kylin://127.0.0.1:7070/learn_kylin
kylin.fieldIde=ORIGINAL
kylin.catalog.primary=false
kylin.catalog.jdbcDriverRequired=true
kylin.catalog.driverMaven=org.apache.kylin:kylin-jdbc:5.0.3
kylin.catalog.defaultDriverClassOverride=org.apache.kylin.jdbc.Driver

# STARROCKS
starrocks.quote=`
starrocks.displayName=StarRocks
starrocks.driver=com.mysql.cj.jdbc.Driver
starrocks.port=9030
starrocks.sql=/* ping */ SELECT 1
starrocks.urlPrefix=jdbc:mysql://
starrocks.url=jdbc:mysql://{host}[:{port}]/[{database}][\?{params}]
starrocks.sample=jdbc:mysql://127.0.0.1:9030/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&rewriteBatchedStatements=true&useCompression=true
starrocks.fieldIde=ORIGINAL
starrocks.catalog.primary=false
starrocks.catalog.jdbcDriverRequired=true
starrocks.catalog.driverMaven=com.mysql:mysql-connector-j:8.4.0
starrocks.catalog.defaultDriverClassOverride=

# GREENPLUM
greenplum.quote="
greenplum.displayName=Greenplum
greenplum.driver=org.postgresql.Driver
greenplum.port=5432
greenplum.sql=SELECT 1
greenplum.urlPrefix=jdbc:postgresql://
greenplum.url=jdbc:postgresql://{host}[:{port}]/[{database}][\?{params}]
greenplum.sample=jdbc:postgresql://127.0.0.1:5432/test
greenplum.fieldIde=ORIGINAL
greenplum.catalog.primary=false
greenplum.catalog.jdbcDriverRequired=true
greenplum.catalog.driverMaven=org.postgresql:postgresql:42.7.4
greenplum.catalog.defaultDriverClassOverride=

# DORIS
doris.quote=`
doris.displayName=Doris
doris.driver=com.mysql.cj.jdbc.Driver
doris.port=9030
doris.sql=/* ping */ SELECT 1
doris.urlPrefix=jdbc:mysql://
doris.url=jdbc:mysql://{host}[:{port}]/[{database}][\?{params}]
doris.sample=jdbc:mysql://127.0.0.1:9030/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&rewriteBatchedStatements=true&useCompression=true
doris.fieldIde=ORIGINAL
doris.catalog.primary=false
doris.catalog.jdbcDriverRequired=true
doris.catalog.driverMaven=com.mysql:mysql-connector-j:8.4.0
doris.catalog.defaultDriverClassOverride=

# OCEANBASE
oceanbase.quote=`
oceanbase.displayName=OceanBase
oceanbase.driver=com.oceanbase.jdbc.Driver
oceanbase.port=2881
oceanbase.sql=/* ping */ SELECT 1
oceanbase.urlPrefix=jdbc:oceanbase://
oceanbase.url=jdbc:oceanbase://{host}[:{port}]/[{database}][\?{params}]
oceanbase.sample=jdbc:oceanbase://127.0.0.1:2881/test?pool=false&useUnicode=true&characterEncoding=utf-8&useSSL=false
oceanbase.fieldIde=ORIGINAL
oceanbase.catalog.primary=false
oceanbase.catalog.jdbcDriverRequired=true
oceanbase.catalog.driverMaven=com.oceanbase:oceanbase-client:2.4.14
oceanbase.catalog.defaultDriverClassOverride=com.oceanbase.jdbc.Driver

# TDENGINE
tdengine.quote=
tdengine.displayName=TDengine
tdengine.driver=com.taosdata.jdbc.rs.RestfulDriver
tdengine.port=6041
tdengine.sql=/* ping */ SELECT 1
tdengine.urlPrefix=jdbc:TAOS-RS://
tdengine.url=jdbc:TAOS-RS://{host}[:{port}]/[{database}][\?{params}]
tdengine.sample=jdbc:TAOS-RS://127.0.0.1:6041/test?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC+8
tdengine.fieldIde=ORIGINAL
tdengine.catalog.primary=false
tdengine.catalog.jdbcDriverRequired=true
tdengine.catalog.driverMaven=com.taosdata.jdbc:taos-jdbc:3.3.2
tdengine.catalog.defaultDriverClassOverride=com.taosdata.jdbc.rs.RestfulDriver

# TRINO
trino.quote="
trino.displayName=Trino
trino.driver=io.trino.jdbc.TrinoDriver
trino.port=8080
trino.sql=/* ping */ SELECT 1
trino.urlPrefix=jdbc:trino://
trino.url=jdbc:trino://{host}[:{port}]/[{catalog}][/{schema}][\?{params}]
trino.sample=jdbc:trino://127.0.0.1:8080/hive/default
trino.fieldIde=ORIGINAL
trino.catalog.primary=false
trino.catalog.jdbcDriverRequired=true
trino.catalog.driverMaven=io.trino:trino-jdbc:481
trino.catalog.defaultDriverClassOverride=

# PRESTO
presto.quote="
presto.displayName=presto
presto.driver=io.prestosql.jdbc.PrestoDriver
presto.port=18080
presto.sql=/* ping */ SELECT 1
presto.urlPrefix=jdbc:presto://
presto.url=jdbc:presto://{host}[:{port}]
presto.sample=jdbc:presto://127.0.0.1:18080
presto.fieldIde=ORIGINAL
presto.catalog.primary=false
presto.catalog.jdbcDriverRequired=true
presto.catalog.driverMaven=com.facebook.presto:presto-jdbc:0.284.1
presto.catalog.defaultDriverClassOverride=io.prestosql.jdbc.PrestoDriver

# HSQL
hsql.quote="
hsql.displayName=HSQLDB
hsql.driver=org.hsqldb.jdbc.JDBCDriver
hsql.port=9001
hsql.sql=SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
hsql.urlPrefix=jdbc:hsqldb:
hsql.url=jdbc:hsqldb://{host}[:{port}]/[{database}][\?{params}]
hsql.sample=jdbc:hsqldb://127.0.0.1:9001/test
hsql.fieldIde=ORIGINAL
hsql.catalog.primary=false
hsql.catalog.jdbcDriverRequired=true
hsql.catalog.driverMaven=org.hsqldb:hsqldb:2.7.3
hsql.catalog.defaultDriverClassOverride=org.hsqldb.jdbc.JDBCDriver

# H2
h2.quote="
h2.displayName=H2
h2.driver=org.h2.Driver
h2.port=9092
h2.sql=SELECT 1
h2.urlPrefix=jdbc:h2:
h2.url=jdbc:h2:tcp://{host}[:{port}]/[{database}][\?{params}]
h2.sample=jdbc:h2:tcp://127.0.0.1:9092/test
h2.fieldIde=ORIGINAL
h2.catalog.primary=false
h2.catalog.jdbcDriverRequired=true
h2.catalog.driverMaven=com.h2database:h2:2.2.224
h2.catalog.defaultDriverClassOverride=org.h2.Driver

# CACHEDB
cachedb.quote="
cachedb.displayName=Cache
cachedb.driver=com.intersys.jdbc.CacheDriver
cachedb.port=1972
cachedb.sql=SELECT 1
cachedb.urlPrefix=jdbc:Cache://
cachedb.url=jdbc:Cache://{host}[:{port}]
cachedb.sample=jdbc:Cache://127.0.0.1:1972
cachedb.fieldIde=ORIGINAL
cachedb.catalog.primary=false
cachedb.catalog.jdbcDriverRequired=true
cachedb.catalog.driverMaven=com.intersys:cache-jdbc:2018.1.4
cachedb.catalog.defaultDriverClassOverride=com.intersys.jdbc.CacheDriver

# PHOENIX
phoenix.quote="
phoenix.displayName=Phoenix
phoenix.driver=org.apache.phoenix.queryserver.client.Driver
phoenix.port=8765
phoenix.sql=SELECT 1
phoenix.urlPrefix=jdbc:phoenix:
phoenix.url=jdbc:phoenix:{host}[:{port}]
phoenix.sample=jdbc:phoenix:127.0.0.1:8765
phoenix.fieldIde=ORIGINAL
phoenix.catalog.primary=false
phoenix.catalog.jdbcDriverRequired=true
phoenix.catalog.driverMaven=org.apache.phoenix:phoenix-queryserver-client:6.0.0
phoenix.catalog.defaultDriverClassOverride=org.apache.phoenix.queryserver.client.Driver

# KAFKA
kafka.quote=
kafka.displayName=Kafka
kafka.driver=
kafka.port=9092
kafka.sql=
kafka.urlPrefix=
kafka.url=
kafka.sample=
kafka.fieldIde=ORIGINAL
kafka.catalog.kind=nonJdbc
kafka.catalog.primary=true
kafka.catalog.jdbcDriverRequired=false
kafka.catalog.driverMaven=
kafka.catalog.defaultDriverClassOverride=

# TIDB
tidb.quote=`
tidb.displayName=TiDB
tidb.driver=com.mysql.jdbc.Driver
tidb.port=9030
tidb.sql=/* ping */ SELECT 1
tidb.urlPrefix=jdbc:mysql://
tidb.url=jdbc:mysql://{host}[:{port}]/[{database}][\?{params}]
tidb.sample=jdbc:mysql://127.0.0.1:9030/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&rewriteBatchedStatements=true&useCompression=true
tidb.fieldIde=ORIGINAL
tidb.catalog.primary=false
tidb.catalog.jdbcDriverRequired=true
tidb.catalog.driverMaven=com.mysql:mysql-connector-j:8.4.0
tidb.catalog.defaultDriverClassOverride=com.mysql.cj.jdbc.Driver

# REDIS
redis.quote=
redis.displayName=Redis
redis.driver=
redis.port=6379
redis.sql=
redis.urlPrefix=
redis.sample=
redis.fieldIde=ORIGINAL
redis.catalog.kind=nonJdbc
redis.catalog.primary=true
redis.catalog.jdbcDriverRequired=false
redis.catalog.driverMaven=
redis.catalog.defaultDriverClassOverride=

# FLINK
flink.quote="
flink.displayName=Flink
flink.driver=org.apache.flink.table.jdbc.FlinkDriver
flink.port=8083
flink.sql=SELECT 1
flink.urlPrefix=jdbc:flink://
flink.url=jdbc:flink://{host}[:{port}][\?{params}]
flink.sample=jdbc:flink://127.0.0.1:8083
flink.fieldIde=ORIGINAL
flink.catalog.primary=false
flink.catalog.jdbcDriverRequired=true
flink.catalog.driverMaven=org.apache.flink:flink-sql-jdbc-driver-bundle:1.20.1
flink.catalog.defaultDriverClassOverride=org.apache.flink.table.jdbc.FlinkDriver

# GAUSSDB
gaussdb.quote="
gaussdb.displayName=GaussDB
gaussdb.driver=com.huawei.gaussdb.jdbc.Driver
gaussdb.port=8000
gaussdb.sql=SELECT 1
gaussdb.urlPrefix=jdbc:gaussdb://
gaussdb.url=jdbc:gaussdb://{host}[:{port}]/[{database}][\?{params}]
gaussdb.sample=jdbc:gaussdb://127.0.0.1:8000/postgres
gaussdb.fieldIde=ORIGINAL
gaussdb.catalog.primary=false
gaussdb.catalog.jdbcDriverRequired=true
gaussdb.catalog.driverMaven=com.huaweicloud.gaussdb:gaussdbjdbc:506.0.0.b058
gaussdb.catalog.defaultDriverClassOverride=com.huawei.gaussdb.jdbc.Driver

# OTHER
other.quote=`
other.displayName=Other JDBC
other.driver=
other.port=10000
other.sql=
other.urlPrefix=
other.url=jdbc:{subprotocol}://{host}[:{port}]/[{database}][\?{params}]
other.sample=jdbc:other://127.0.0.1:10000
other.fieldIde=ORIGINAL
other.catalog.kind=jdbcCustom
other.catalog.primary=false
other.catalog.jdbcDriverRequired=true
other.catalog.driverMaven=
other.catalog.defaultDriverClassOverride=
