package org.apache.datawise.backend.connector.postgresql.support;

import org.apache.datawise.backend.connector.postgresql.ddl.PostgresqlDdlRenderer;
import org.apache.datawise.backend.connector.postgresql.parser.PostgresqlLogicalTypeParser;
import org.apache.datawise.backend.connector.postgresql.schema.PostgresqlSchemaDialect;
import org.apache.datawise.backend.metadata.ColumnDefinition;
import org.apache.datawise.backend.metadata.LogicalType;
import org.apache.datawise.backend.metadata.LogicalTypeKind;
import org.apache.datawise.backend.metadata.PrimaryKeyDefinition;
import org.apache.datawise.backend.metadata.TableDefinition;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class PostgresqlTableIntrospectorTest {

    @Test
    void renderDataTypeFormatsCommonTypes() {
        assertEquals("varchar(100)", PostgresqlTableIntrospector.renderDataType(
                new LogicalType(LogicalTypeKind.VARCHAR, 100, null, null, false, "varchar", Map.of())));
        assertEquals("integer", PostgresqlTableIntrospector.renderDataType(
                new LogicalType(LogicalTypeKind.INTEGER, null, null, null, false, "int4", Map.of())));
        assertEquals("jsonb", PostgresqlTableIntrospector.renderDataType(
                new LogicalType(LogicalTypeKind.JSON, null, null, null, false, "jsonb", Map.of())));
    }

    @Test
    void logicalTypeParserMapsPostgresqlUdtNames() {
        PostgresqlLogicalTypeParser parser = new PostgresqlLogicalTypeParser();
        LogicalType varchar = parser.fromUdt("varchar", 255, null, null);
        assertEquals(LogicalTypeKind.VARCHAR, varchar.kind());
        assertEquals(255, varchar.length());

        LogicalType numeric = parser.fromUdt("numeric", null, 10, 2);
        assertEquals(LogicalTypeKind.DECIMAL, numeric.kind());
        assertEquals(10, numeric.precision());
        assertEquals(2, numeric.scale());
    }

    @Test
    void renderCreateTableIncludesPrimaryKey() {
        PostgresqlTableIntrospector introspector = new PostgresqlTableIntrospector(
                new PostgresqlSchemaDialect(),
                new PostgresqlDdlRenderer()
        );
        TableDefinition definition = new TableDefinition(
                "app",
                "public",
                "users",
                List.of(new ColumnDefinition(
                        "id",
                        new LogicalType(LogicalTypeKind.INTEGER, null, null, null, false, "int4", Map.of()),
                        false,
                        null,
                        true,
                        null,
                        1
                )),
                new PrimaryKeyDefinition("users_pkey", List.of("id")),
                List.of(),
                List.of(),
                Map.of(),
                null
        );
        String ddl = introspector.renderCreateTable(definition);
        assertTrue(ddl.contains("CREATE TABLE \"public\".\"users\""));
        assertTrue(ddl.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(ddl.contains("PRIMARY KEY (\"id\")"));
    }
}
