package org.apache.datawise.backend.ai.semantic;

import org.apache.datawise.backend.ai.tag.AiTableTagService;
import org.apache.datawise.backend.configstore.SemanticMetricStore;
import org.apache.datawise.backend.database.table.TableDetailService;
import org.apache.datawise.backend.domain.AutoGenerateSemanticMetricsRequest;
import org.apache.datawise.backend.domain.SemanticMetricDto;
import org.apache.datawise.backend.domain.TableColumnDetail;
import org.apache.datawise.backend.domain.TablePropertiesResult;
import org.apache.datawise.backend.model.ConnectionEntity;
import org.apache.datawise.backend.model.SemanticMetricEntry;
import org.apache.datawise.backend.service.ConnectionVisibilityService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class SemanticLayerServiceTest {

    private SemanticMetricStore metricStore;
    private TableDetailService tableDetailService;
    private ConnectionVisibilityService connectionVisibilityService;
    private AiTableTagService tableTagService;
    private SemanticLayerService service;

    @BeforeEach
    void setUp() {
        metricStore = mock(SemanticMetricStore.class);
        tableDetailService = mock(TableDetailService.class);
        connectionVisibilityService = mock(ConnectionVisibilityService.class);
        tableTagService = mock(AiTableTagService.class);
        service = new SemanticLayerService(
                metricStore,
                tableDetailService,
                connectionVisibilityService,
                tableTagService
        );
    }

    @Test
    void autoGenerateDoesNotDuplicateExistingGeneratedNames() {
        when(connectionVisibilityService.resolveConnectionEntity("conn-1"))
                .thenReturn(Optional.of(connection("conn-1")));
        when(metricStore.listScoped("conn-1", "shop"))
                .thenReturn(List.of(metric("metric-1", "orders \u8868"), metric("metric-2", "orders.amount")));
        when(tableTagService.listTaggedTableNames("conn-1", "shop"))
                .thenReturn(List.of("orders"));
        when(tableDetailService.loadProperties("orders", "conn-1", "shop"))
                .thenReturn(new TablePropertiesResult(
                        "orders",
                        "orders table",
                        null,
                        null,
                        null,
                        null,
                        List.of(column("amount", "order amount")),
                        List.of(),
                        List.of()
                ));

        List<SemanticMetricDto> result = service.autoGenerate(
                new AutoGenerateSemanticMetricsRequest("conn-1", "shop")
        );

        assertEquals(2, result.size());
        verify(metricStore, never()).upsert(any(SemanticMetricEntry.class));
    }

    private static ConnectionEntity connection(String id) {
        ConnectionEntity entity = new ConnectionEntity();
        entity.setId(id);
        return entity;
    }

    private static SemanticMetricEntry metric(String id, String name) {
        SemanticMetricEntry entry = new SemanticMetricEntry();
        entry.setId(id);
        entry.setName(name);
        return entry;
    }

    private static TableColumnDetail column(String name, String comment) {
        return new TableColumnDetail(1, name, "decimal", true, false, null, null, null, comment);
    }
}