package org.apache.datawise.backend.ai.semantic;

import org.apache.datawise.backend.ai.tag.AiTableTagService;
import org.apache.datawise.backend.configstore.SemanticMetricStore;
import org.apache.datawise.backend.database.table.TableDetailService;
import org.apache.datawise.backend.domain.AutoGenerateSemanticMetricsRequest;
import org.apache.datawise.backend.domain.SaveSemanticMetricRequest;
import org.apache.datawise.backend.domain.SemanticMetricDto;
import org.apache.datawise.backend.domain.TableColumnDetail;
import org.apache.datawise.backend.domain.TablePropertiesResult;
import org.apache.datawise.backend.model.ConnectionEntity;
import org.apache.datawise.backend.model.SemanticMetricEntry;
import org.apache.datawise.backend.service.ConnectionVisibilityService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class SemanticLayerServiceTest {

    private SemanticMetricStore metricStore;
    private TableDetailService tableDetailService;
    private ConnectionVisibilityService connectionVisibilityService;
    private AiTableTagService tableTagService;
    private SemanticLayerService service;

    @BeforeEach
    void setUp() {
        metricStore = mock(SemanticMetricStore.class);
        tableDetailService = mock(TableDetailService.class);
        connectionVisibilityService = mock(ConnectionVisibilityService.class);
        tableTagService = mock(AiTableTagService.class);
        service = new SemanticLayerService(
                metricStore,
                tableDetailService,
                connectionVisibilityService,
                tableTagService
        );
    }

    @Test
    void autoGenerateDoesNotDuplicateExistingGeneratedNames() {
        when(connectionVisibilityService.resolveConnectionEntity("conn-1"))
                .thenReturn(Optional.of(connection("conn-1")));
        when(metricStore.listScoped("conn-1", "shop"))
                .thenReturn(List.of(metric("metric-1", "orders \u8868"), metric("metric-2", "orders.amount")));
        when(tableTagService.listTaggedTableNames("conn-1", "shop"))
                .thenReturn(List.of("orders"));
        when(tableDetailService.loadProperties("orders", "conn-1", "shop"))
                .thenReturn(new TablePropertiesResult(
                        "orders",
                        "orders table",
                        null,
                        null,
                        null,
                        null,
                        List.of(column("amount", "order amount")),
                        List.of(),
                        List.of()
                ));

        List<SemanticMetricDto> result = service.autoGenerate(
                new AutoGenerateSemanticMetricsRequest("conn-1", "shop")
        );

        assertEquals(2, result.size());
        verify(metricStore, never()).upsert(any(SemanticMetricEntry.class));
    }

    @Test
    void saveIncrementsDefinitionVersionWhenExpressionChanges() {
        SemanticMetricEntry existing = new SemanticMetricEntry();
        existing.setId("metric-1");
        existing.setName("gmv");
        existing.setExpression("sum(amount)");
        existing.setDefinitionVersion(2);
        existing.setDefinitionUpdatedAt(1000L);
        when(metricStore.listAll()).thenReturn(List.of(existing));
        when(metricStore.upsert(any(SemanticMetricEntry.class))).thenAnswer(invocation -> invocation.getArgument(0));

        SemanticMetricDto saved = service.save(new SaveSemanticMetricRequest(
                "metric-1",
                "conn-1",
                "shop",
                "gmv",
                "sum(paid_amount)",
                "gross merchandise value",
                "CNY",
                List.of("orders"),
                List.of("order_amount"),
                "switch to paid amount",
                "alice",
                List.of("kpi", "finance")
        ));

        assertEquals(3, saved.definitionVersion());
        assertEquals("switch to paid amount", saved.latestChangeNote());
        assertTrue(saved.definitionUpdatedAt() != null && saved.definitionUpdatedAt() > 1000L);
    }

    @Test
    void saveKeepsDefinitionVersionWhenExpressionUnchanged() {
        SemanticMetricEntry existing = new SemanticMetricEntry();
        existing.setId("metric-1");
        existing.setName("gmv");
        existing.setExpression("sum(amount)");
        existing.setDefinitionVersion(2);
        existing.setDefinitionUpdatedAt(1000L);
        when(metricStore.listAll()).thenReturn(List.of(existing));
        when(metricStore.upsert(any(SemanticMetricEntry.class))).thenAnswer(invocation -> invocation.getArgument(0));

        SemanticMetricDto saved = service.save(new SaveSemanticMetricRequest(
                "metric-1",
                "conn-1",
                "shop",
                "gmv",
                "sum(amount)",
                "gross merchandise value",
                "CNY",
                List.of("orders"),
                List.of("order_amount"),
                "text tweak only",
                null,
                null
        ));

        assertEquals(2, saved.definitionVersion());
    }

    private static ConnectionEntity connection(String id) {
        ConnectionEntity entity = new ConnectionEntity();
        entity.setId(id);
        return entity;
    }

    private static SemanticMetricEntry metric(String id, String name) {
        SemanticMetricEntry entry = new SemanticMetricEntry();
        entry.setId(id);
        entry.setName(name);
        return entry;
    }

    private static TableColumnDetail column(String name, String comment) {
        return new TableColumnDetail(1, name, "decimal", true, false, null, null, null, comment);
    }
}