/** DDL 列定义常用 SQL 数据类型（CREATE TABLE / ALTER COLUMN） */
export const SQL_DDL_COLUMN_TYPES = [
    'BIGINT',
    'INT',
    'INTEGER',
    'SMALLINT',
    'TINYINT',
    'MEDIUMINT',
    'VARCHAR',
    'CHAR',
    'TEXT',
    'BLOB',
    'LONGTEXT',
    'MEDIUMTEXT',
    'TINYTEXT',
    'DECIMAL',
    'NUMERIC',
    'FLOAT',
    'DOUBLE',
    'REAL',
    'BOOLEAN',
    'BOOL',
    'BIT',
    'DATE',
    'TIME',
    'DATETIME',
    'TIMESTAMP',
    'YEAR',
    'JSON',
    'UUID',
    'BINARY',
    'VARBINARY',
    'ENUM',
    'SET',
] as const

export type SqlDdlColumnType = (typeof SQL_DDL_COLUMN_TYPES)[number]
