package org.apache.datawise.backend.domain;

import org.apache.datawise.backend.model.SemanticMetricEntry;

import java.util.List;

public record SemanticMetricDto(
        String id,
        String connectionId,
        String database,
        String name,
        String expression,
        String description,
        String unit,
        List<String> relatedTables,
        boolean autoGenerated
) {
    public static SemanticMetricDto from(SemanticMetricEntry entry) {
        return new SemanticMetricDto(
                entry.getId(),
                entry.getConnectionId(),
                entry.getDatabase(),
                entry.getName(),
                entry.getExpression(),
                entry.getDescription(),
                entry.getUnit(),
                entry.getRelatedTables(),
                entry.isAutoGenerated()
        );
    }
}
