package org.apache.datawise.backend.model;

import java.util.ArrayList;
import java.util.List;

/**
 * 语义层业务指标定义（config/users/{id}/semantic-metrics.json）。
 */
public class SemanticMetricEntry {

    private String id;
    private String connectionId;
    private String database;
    private String name;
    private String expression;
    private String description;
    private String unit;
    /** Optional owner / steward for org discovery (free-form display name). */
    private String owner;
    /** Free-form tags for org discovery facets (normalized on write). */
    private List<String> tags = new ArrayList<>();
    private List<String> relatedTables = new ArrayList<>();
    private List<String> upstreamMetrics = new ArrayList<>();
    private Integer definitionVersion;
    private Long definitionUpdatedAt;
    private String latestChangeNote;
    private boolean autoGenerated;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getConnectionId() {
        return connectionId;
    }

    public void setConnectionId(String connectionId) {
        this.connectionId = connectionId;
    }

    public String getDatabase() {
        return database;
    }

    public void setDatabase(String database) {
        this.database = database;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getExpression() {
        return expression;
    }

    public void setExpression(String expression) {
        this.expression = expression;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public List<String> getTags() {
        return tags;
    }

    public void setTags(List<String> tags) {
        this.tags = tags != null ? new ArrayList<>(tags) : new ArrayList<>();
    }

    public List<String> getRelatedTables() {
        return relatedTables;
    }

    public void setRelatedTables(List<String> relatedTables) {
        this.relatedTables = relatedTables != null ? new ArrayList<>(relatedTables) : new ArrayList<>();
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public List<String> getUpstreamMetrics() {
        return upstreamMetrics;
    }

    public void setUpstreamMetrics(List<String> upstreamMetrics) {
        this.upstreamMetrics = upstreamMetrics != null ? new ArrayList<>(upstreamMetrics) : new ArrayList<>();
    }

    public Integer getDefinitionVersion() {
        return definitionVersion;
    }

    public void setDefinitionVersion(Integer definitionVersion) {
        this.definitionVersion = definitionVersion;
    }

    public Long getDefinitionUpdatedAt() {
        return definitionUpdatedAt;
    }

    public void setDefinitionUpdatedAt(Long definitionUpdatedAt) {
        this.definitionUpdatedAt = definitionUpdatedAt;
    }

    public String getLatestChangeNote() {
        return latestChangeNote;
    }

    public void setLatestChangeNote(String latestChangeNote) {
        this.latestChangeNote = latestChangeNote;
    }
}
