package org.apache.datawise.backend.connector.postgresql.ddl;

import org.apache.datawise.backend.common.DbType;
import org.apache.datawise.backend.ddl.DdlRenderOptions;
import org.apache.datawise.backend.ddl.render.DialectSqlSupport;
import org.apache.datawise.backend.ddl.spi.DialectDdlRenderer;
import org.apache.datawise.backend.metadata.ColumnDefinition;
import org.apache.datawise.backend.metadata.LogicalType;
import org.apache.datawise.backend.metadata.LogicalTypeKind;
import org.apache.datawise.backend.metadata.TableDefinition;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/** PostgreSQL 协议族 DDL 渲染。 */
public class PostgresqlDdlRenderer implements DialectDdlRenderer {

    private static final Set<String> SUPPORTED = DbType.postgresqlFamilyIds();

    @Override
    public String dialectId() {
        return "postgresql";
    }

    @Override
    public boolean supports(String dbType) {
        return dbType != null && SUPPORTED.contains(DbType.normalizeId(dbType));
    }

    @Override
    public int priority() {
        return 20;
    }

    @Override
    public String renderCreateTable(TableDefinition definition, DdlRenderOptions options) {
        String schema = resolveSchema(definition, options);
        String qualified = DialectSqlSupport.quoteDouble(schema) + "."
                + DialectSqlSupport.quoteDouble(definition.name());
        List<String> lines = new ArrayList<>();
        for (ColumnDefinition column : definition.columns()) {
            lines.add("  " + renderColumn(column));
        }
        if (definition.primaryKey() != null && !definition.primaryKey().columnNames().isEmpty()) {
            lines.add("  CONSTRAINT " + DialectSqlSupport.quoteDouble(definition.primaryKey().name())
                    + " PRIMARY KEY ("
                    + String.join(", ", definition.primaryKey().columnNames().stream()
                    .map(DialectSqlSupport::quoteDouble).toList())
                    + ")");
        }
        return "CREATE TABLE " + qualified + " (\n" + String.join(",\n", lines) + "\n);";
    }

    @Override
    public String renderPhysicalType(LogicalType type) {
        if (type == null) {
            return "text";
        }
        String raw = type.rawTypeName();
        if (raw != null && !raw.isBlank() && type.kind() == LogicalTypeKind.UNKNOWN) {
            return raw;
        }
        return switch (type.kind()) {
            case TINYINT, SMALLINT -> "smallint";
            case INTEGER -> "integer";
            case BIGINT -> "bigint";
            case DECIMAL -> DialectSqlSupport.renderDecimal("numeric", type);
            case FLOAT -> "real";
            case DOUBLE -> "double precision";
            case CHAR -> type.length() != null ? "char(" + type.length() + ")" : "char(1)";
            case VARCHAR -> type.length() != null ? "varchar(" + type.length() + ")" : "varchar";
            case TEXT, ENUM, SET -> "text";
            case BLOB, BINARY, VARBINARY -> "bytea";
            case BOOLEAN -> "boolean";
            case DATE -> "date";
            case TIME -> "time";
            case DATETIME, TIMESTAMP -> "timestamp";
            case JSON -> "jsonb";
            case UUID -> "uuid";
            default -> raw != null && !raw.isBlank() ? raw : type.kind().name().toLowerCase(Locale.ROOT);
        };
    }

    private String renderColumn(ColumnDefinition column) {
        StringBuilder sb = new StringBuilder();
        sb.append(DialectSqlSupport.quoteDouble(column.name()))
                .append(' ')
                .append(renderPhysicalType(column.type()));
        if (!column.nullable()) {
            sb.append(" NOT NULL");
        }
        if (column.autoIncrement()) {
            sb.append(" GENERATED BY DEFAULT AS IDENTITY");
        } else if (column.defaultExpression() != null && !column.defaultExpression().isBlank()) {
            sb.append(" DEFAULT ").append(column.defaultExpression());
        }
        return sb.toString();
    }

    private static String resolveSchema(TableDefinition definition, DdlRenderOptions options) {
        if (options != null && options.targetDatabase() != null && !options.targetDatabase().isBlank()) {
            return options.targetDatabase();
        }
        if (definition.schema() != null && !definition.schema().isBlank()) {
            return definition.schema();
        }
        return "public";
    }
}
