import type {ShortcutDefinition} from '@/core/shortcuts/types'

export const SHORTCUT_DEFINITIONS: ShortcutDefinition[] = [
    {
        id: 'explorer.search',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.search',
        defaultBinding: 'Ctrl+F',
        icon: 'search',
    },
    {
        id: 'explorer.refresh',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.refresh',
        defaultBinding: 'F5',
        icon: 'refresh',
    },
    {
        id: 'explorer.locate',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.locate',
        defaultBinding: 'Alt+Shift+L',
        icon: 'locate',
    },
    {
        id: 'explorer.openNode',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.openNode',
        defaultBinding: 'F4',
        icon: 'open',
    },
    {
        id: 'explorer.editNode',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.editNode',
        defaultBinding: 'F6',
        icon: 'edit',
    },
    {
        id: 'explorer.deleteNode',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.deleteNode',
        defaultBinding: 'Delete',
        icon: 'delete',
    },
    {
        id: 'explorer.openDatabaseSql',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.openDatabaseSql',
        defaultBinding: 'F3',
        icon: 'console',
    },
    {
        id: 'explorer.openRecentDatabaseSql',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.openRecentDatabaseSql',
        defaultBinding: 'Ctrl+Enter',
        icon: 'file',
    },
    {
        id: 'explorer.newDatabaseSql',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.newDatabaseSql',
        defaultBinding: 'Ctrl+]',
        icon: 'file',
    },
    {
        id: 'explorer.openDatabaseConsole',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.openDatabaseConsole',
        defaultBinding: 'Ctrl+Alt+Enter',
        icon: 'console',
    },
    {
        id: 'explorer.toggleColumnComment',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.toggleColumnComment',
        defaultBinding: '',
        icon: 'comment-column',
    },
    {
        id: 'explorer.toggleTableComment',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.toggleTableComment',
        defaultBinding: '',
        icon: 'comment-table',
    },
    {
        id: 'explorer.toggleAllComments',
        category: 'explorer',
        labelKey: 'shortcuts.actions.explorer.toggleAllComments',
        defaultBinding: 'Ctrl+Shift+C',
        icon: 'comment-all',
    },
    {
        id: 'workspace.newConsole',
        category: 'workspace',
        labelKey: 'shortcuts.actions.workspace.newConsole',
        defaultBinding: 'Ctrl+Shift+L',
        icon: 'console',
    },
    {
        id: 'workspace.runSql',
        category: 'workspace',
        labelKey: 'shortcuts.actions.workspace.runSql',
        defaultBinding: 'Ctrl+R',
        icon: 'run',
    },
    {
        id: 'workspace.saveConsole',
        category: 'workspace',
        labelKey: 'shortcuts.actions.workspace.saveConsole',
        defaultBinding: 'Ctrl+S',
        icon: 'save',
    },
    {
        id: 'workspace.aiPrompt',
        category: 'workspace',
        labelKey: 'shortcuts.actions.workspace.aiPrompt',
        defaultBinding: '/',
        icon: 'ai',
    },
    {
        id: 'app.openSettings',
        category: 'app',
        labelKey: 'shortcuts.actions.app.openSettings',
        defaultBinding: 'Ctrl+,',
        icon: 'settings',
    },
    {
        id: 'app.toggleTerminal',
        category: 'app',
        labelKey: 'shortcuts.actions.app.toggleTerminal',
        defaultBinding: 'Ctrl+`',
        icon: 'terminal',
    },
    {
        id: 'app.toggleNotifications',
        category: 'app',
        labelKey: 'shortcuts.actions.app.toggleNotifications',
        defaultBinding: 'Ctrl+Shift+N',
        icon: 'notify',
    },
    {
        id: 'app.globalObjectSearch',
        category: 'app',
        labelKey: 'shortcuts.actions.app.globalObjectSearch',
        defaultBinding: 'Ctrl+Shift+O',
        icon: 'search',
    },
]

export const SHORTCUT_ACTION_IDS = SHORTCUT_DEFINITIONS.map((item) => item.id)
