import type {ExecuteSqlResult} from '@/shared/api/types'

export type PlatformFeatureId =
    | 'semantic_metrics'
    | 'analysis_canvas'
    | 'federated_views'
    | 'schema_drift'
    | 'data_quality'
    | 'scheduled_tasks'

export interface AiCanvasParameter {
    key: string
    label?: string | null
    defaultValue?: string | null
    type?: string | null
}

export interface AnalysisCanvasSummary {
    id: string
    title: string
    description?: string | null
    parameterCount: number
    createdAt?: string | null
    updatedAt?: string | null
}

export interface AnalysisCanvasDetail {
    id: string
    title: string
    description?: string | null
    promptTemplate?: string | null
    parameters?: AiCanvasParameter[] | null
    sql?: string | null
    summary?: string | null
    chartSpecJson?: string | null
    reportMarkdown?: string | null
    targetsJson?: string | null
    createdAt?: string | null
    updatedAt?: string | null
}

export interface SaveAnalysisCanvasRequest {
    id?: string | null
    title: string
    description?: string | null
    promptTemplate?: string | null
    parameters?: AiCanvasParameter[] | null
    sql?: string | null
    summary?: string | null
    chartSpecJson?: string | null
    reportMarkdown?: string | null
    targetsJson?: string | null
}

export interface RerunAnalysisCanvasRequest {
    canvasId: string
    parameterValues?: Record<string, string> | null
}

export interface RerunAnalysisCanvasResult {
    canvasId: string
    title: string
    prompt: string
    sql: string
    targetsJson?: string | null
}

export interface SemanticMetric {
    id: string
    connectionId: string
    database: string
    name: string
    expression: string
    description?: string | null
    unit?: string | null
    owner?: string | null
    relatedTables?: string[] | null
    upstreamMetrics?: string[] | null
    definitionVersion?: number | null
    definitionUpdatedAt?: number | null
    latestChangeNote?: string | null
    autoGenerated: boolean
}

export interface SaveSemanticMetricRequest {
    id?: string | null
    connectionId: string
    database: string
    name: string
    expression: string
    description?: string | null
    unit?: string | null
    owner?: string | null
    relatedTables?: string[] | null
    upstreamMetrics?: string[] | null
    changeNote?: string | null
}

export interface AutoGenerateSemanticMetricsRequest {
    connectionId: string
    database: string
}

/** Org-level discovery hit from schema cache + semantic metrics. */
export interface DiscoveryHit {
    kind: 'table' | 'view' | 'metric'
    id: string
    name: string
    qualifiedLabel: string
    connectionId: string
    connectionLabel: string
    database: string
    owner?: string | null
    subtitle?: string | null
    score: number
    /** Metric-only: related physical tables for lineage jump. */
    relatedTables?: string[] | null
}

/** Paginated discovery search / browse response. */
export interface DiscoverySearchPage {
    hits: DiscoveryHit[]
    total: number
    offset: number
    limit: number
    hasMore: boolean
}

export interface SqlReviewRequest {
    sql: string
    connectionId?: string | null
    database?: string | null
    aiRewrite?: boolean | null
}

export interface SqlReviewFinding {
    severity: string
    code: string
    message: string
    suggestion?: string | null
}

export interface SqlReviewResult {
    allowed: boolean
    requiresApproval: boolean
    findings: SqlReviewFinding[]
    suggestedSql?: string | null
    rewriteNote?: string | null
}

export interface GenerateFederatedSqlRequest {
    prompt: string
    sources: FederatedViewSource[]
}

export interface GenerateFederatedSqlResult {
    sql: string
    summary?: string | null
}

export interface FederatedViewSource {
    alias?: string | null
    connectionId?: string | null
    connectionLabel?: string | null
    database?: string | null
}

export interface FederatedViewSummary {
    id: string
    name: string
    description?: string | null
    sourceCount: number
    updatedAt?: string | null
}

export interface FederatedViewDetail {
    id: string
    name: string
    description?: string | null
    sources?: FederatedViewSource[] | null
    sql?: string | null
    createdAt?: string | null
    updatedAt?: string | null
}

export interface SaveFederatedViewRequest {
    id?: string | null
    name: string
    description?: string | null
    sources?: FederatedViewSource[] | null
    sql?: string | null
}

export interface ExecuteFederatedViewRequest {
    viewId: string
    maxRows?: number | null
}

export interface SchemaDriftMonitor {
    id: string
    name: string
    sourceConnectionId: string
    sourceDatabase: string
    targetConnectionId: string
    targetDatabase: string
    tablePattern?: string | null
    enabled: boolean
    lastCheckedAt?: string | null
    driftCount: number
}

export interface SaveSchemaDriftMonitorRequest {
    id?: string | null
    name: string
    sourceConnectionId: string
    sourceDatabase: string
    targetConnectionId: string
    targetDatabase: string
    tablePattern?: string | null
    enabled?: boolean | null
}

export interface SchemaDriftCompareRequest {
    sourceConnectionId: string
    sourceDatabase: string
    targetConnectionId: string
    targetDatabase: string
    tablePattern?: string | null
}

export interface SchemaDriftTableDiff {
    tableName: string
    status: string
    missingOnTarget?: string[] | null
    extraOnTarget?: string[] | null
    typeMismatches?: string[] | null
    suggestedAlterSql?: string | null
}

export interface SchemaDriftReport {
    sourceConnectionId: string
    sourceDatabase: string
    targetConnectionId: string
    targetDatabase: string
    comparedAt?: string | null
    driftTableCount: number
    tables?: SchemaDriftTableDiff[] | null
}

export interface ScheduledTask {
    id: string
    name: string
    type: string
    cronExpression?: string | null
    payloadJson?: string | null
    enabled: boolean
    lastRunAt?: string | null
    lastRunStatus?: string | null
    lastRunMessage?: string | null
    createdAt?: string | null
    orchestrationState?: string | null
    orchestrationRef?: string | null
    orchestrationCheckedAt?: string | null
    orchestrationDetail?: string | null
}

export interface OrchestrationStatusResult {
    taskId: string
    taskName: string
    state: string
    ref?: string | null
    detail?: string | null
    statusUrl?: string | null
    httpStatus: number
    checkedAt?: string | null
}

export interface SaveScheduledTaskRequest {
    id?: string | null
    name: string
    type: string
    cronExpression?: string | null
    payloadJson?: string | null
    enabled?: boolean | null
}

export interface DataQualityGateRequest {
    ruleIds?: string[] | null
    connectionId?: string | null
    database?: string | null
    blockingOnly?: boolean | null
    referenceConnectionId?: string | null
    referenceDatabase?: string | null
    /** When true (default for multi-env), pair reference rules by name. */
    pairByName?: boolean | null
}

export interface DataQualityRuleRun {
    ruleId: string
    name: string
    blocking: boolean
    status?: string | null
    message?: string | null
    ranAt?: string | null
}

export interface DataQualityGateScopeResult {
    connectionId?: string | null
    database?: string | null
    passed: boolean
    total: number
    failed: number
    results: DataQualityRuleRun[]
}

export interface DataQualityGatePair {
    name: string
    primaryRuleId: string
    referenceRuleId?: string | null
    paired: boolean
}

export interface DataQualityGateResult {
    passed: boolean
    total: number
    failed: number
    results: DataQualityRuleRun[]
    scopes?: DataQualityGateScopeResult[] | null
    pairs?: DataQualityGatePair[] | null
}

/** Tenant-shared data-quality rule template (server). */
export interface DataQualitySharedTemplate {
    id: string
    name: string
    description?: string | null
    sql: string
    assertion: string
    expected?: string | null
    column?: string | null
    blocking: boolean
    cronExpression?: string | null
    createdAt?: string | null
    updatedAt?: string | null
    createdByUserId?: number | null
}

export interface SaveDataQualitySharedTemplateRequest {
    id?: string | null
    name: string
    description?: string | null
    sql: string
    assertion: string
    expected?: string | null
    column?: string | null
    blocking?: boolean | null
    cronExpression?: string | null
}

export interface QueryLibraryVersion {
    queryId: string
    teamId: string
    version: number
    title: string
    sql: string
    changeNote?: string | null
    savedAt?: string | null
    savedByUserId?: number | null
}

export interface SaveQueryLibraryVersionRequest {
    teamId: string
    queryId: string
    title: string
    sql: string
    changeNote?: string | null
}

export type FederatedViewExecuteResult = ExecuteSqlResult
