import {platformApi} from '@/api'
import type {DwDataGridColumn} from '@/core/components/dw-data-grid.types'
import type {PlatformFeatureId} from '@/features/platform/types/platform.types'

export type PlatformCatalogRow = Record<string, unknown> & {id: string}

export async function loadPlatformCatalogRows(
    feature: PlatformFeatureId,
    connectionId: string,
    database: string,
): Promise<PlatformCatalogRow[]> {
    switch (feature) {
        case 'semantic_metrics':
            return (await platformApi.listSemanticMetrics(connectionId, database)).map((item) => ({
                id: item.id,
                name: item.name,
                expression: item.expression ?? '',
                description: item.description ?? '',
                unit: item.unit ?? '',
                autoGenerated: item.autoGenerated,
                relatedTables: (item.relatedTables ?? []).join(', '),
            }))
        case 'analysis_canvas': {
            const items = await platformApi.listAnalysisCanvas()
            return items.map((item) => ({
                id: item.id,
                title: item.title,
                description: item.description ?? '',
                parameterCount: item.parameterCount,
                updatedAt: item.updatedAt ?? '',
            }))
        }
        case 'federated_views': {
            const items = await platformApi.listFederatedViews()
            return items.map((item) => ({
                id: item.id,
                name: item.name,
                description: item.description ?? '',
                sourceCount: item.sourceCount,
                updatedAt: item.updatedAt ?? '',
            }))
        }
        case 'schema_drift': {
            const items = await platformApi.listSchemaDriftMonitors()
            return items
                .filter(
                    (item) =>
                        item.sourceConnectionId === connectionId
                        && item.sourceDatabase.toLowerCase() === database.toLowerCase(),
                )
                .map((item) => ({
                    id: item.id,
                    name: item.name,
                    targetConnectionId: item.targetConnectionId,
                    targetDatabase: item.targetDatabase,
                    tablePattern: item.tablePattern ?? '%',
                    enabled: item.enabled,
                    driftCount: item.driftCount,
                    lastCheckedAt: item.lastCheckedAt ?? '',
                }))
        }
        case 'scheduled_tasks': {
            const items = await platformApi.listScheduledTasks()
            return items.map((item) => ({
                id: item.id,
                name: item.name,
                type: item.type,
                cronExpression: item.cronExpression ?? '',
                enabled: item.enabled,
                lastRunAt: item.lastRunAt ?? '',
                lastRunStatus: item.lastRunStatus ?? '',
            }))
        }
        default:
            return []
    }
}

export function buildPlatformCatalogColumns(
    feature: PlatformFeatureId,
    translate: (key: string, values?: Record<string, unknown>) => string,
): DwDataGridColumn<PlatformCatalogRow>[] {
    const prefix = `workspace.platformCatalog.columns.${feature}`
    const col = (key: string, extra?: Partial<DwDataGridColumn<PlatformCatalogRow>>) => ({
        key,
        label: translate(`${prefix}.${key}`),
        ...extra,
    })
    switch (feature) {
        case 'semantic_metrics':
            return [
                col('name', {mono: true}),
                col('expression', {mono: true}),
                col('description'),
                col('unit'),
                col('relatedTables'),
                col('autoGenerated', {format: (row) => (row.autoGenerated ? translate('common.yes') : translate('common.no'))}),
            ]
        case 'analysis_canvas':
            return [
                col('title'),
                col('description'),
                col('parameterCount', {align: 'right'}),
                col('updatedAt', {mono: true}),
            ]
        case 'federated_views':
            return [
                col('name', {mono: true}),
                col('description'),
                col('sourceCount', {align: 'right'}),
                col('updatedAt', {mono: true}),
            ]
        case 'schema_drift':
            return [
                col('name'),
                col('targetConnectionId', {mono: true}),
                col('targetDatabase'),
                col('tablePattern', {mono: true}),
                col('driftCount', {align: 'right'}),
                col('enabled', {format: (row) => (row.enabled ? translate('common.yes') : translate('common.no'))}),
                col('lastCheckedAt', {mono: true}),
            ]
        case 'scheduled_tasks':
            return [
                col('name'),
                col('type', {mono: true}),
                col('cronExpression', {mono: true}),
                col('enabled', {format: (row) => (row.enabled ? translate('common.yes') : translate('common.no'))}),
                col('lastRunAt', {mono: true}),
                col('lastRunStatus'),
            ]
        default:
            return []
    }
}

export function platformCatalogTabTitle(
    feature: PlatformFeatureId,
    database: string,
    translate: (key: string, values?: Record<string, unknown>) => string,
): string {
    return translate(`workspace.platformCatalog.tabTitle.${feature}`, {database})
}

export function platformFeatureTreeLabel(feature: PlatformFeatureId, translate: (key: string) => string): string {
    return translate(`explorer.treeAiFeatures.${feature}`)
}
